### ISSUE TITLE
SiO2 bulk distorting during Molecular dynamics Simulation in LAMMPS using NNPs generated by SIMPLE-NN

### ISSUE THREAD

**Issue by dkumarrav** [MDIL-SNU/SIMPLE-NN#71]
Hi,
I was able to run the example provided along with SIMPLE-NN and generated potential (NNP) for molecular dynamics. While running molecular dynamics in LAMMPS using NNP, whole structure is distorting. Moreover, I also ran MD using potential file provided still the bulk structure is distorting.
Request you kindly help me in resolving the issue.

**Comment by Nanco-L** [comment]
Hello, dkumarrav.
The presented dataset in `simple-nn` examples folder is not a sufficient dataset for real MD simulation. The dataset is just for practicing to run our code. It only contains snapshots from 1000K MD of amorphous SiO2. If you use SiO2 crystal for testing the example potential, it may provide the wrong result since the example potential doesn't contain the crystal dataset. If not, for more advice, please let me know about your structure that used in your test.

**Comment by dkumarrav** [comment]
Dear Lee,
I have used bulk structure of SiO2 containing 432 atoms to test NNP using LAMMPS (unit cell obtained from materialsproject.org). I have just expanded the unit cell and running MD.

**Comment by Nanco-L** [comment]
Dear dkumarrav.
As I mentioned above, the example potential may not work well in bulk SiO2. If you want to simulate bulk SiO2, you need to add MD snapshots of bulk SiO2.

**Comment by dkumarrav** [comment]
Dear Lee,
Thank you for the response. I will add more dataset and generate NNP for MD
